### ISSUE TITLE
Deployment Checklist

### ISSUE THREAD

**Issue by varlenthegray** [varlenthegray/wcadmin#169]
- [x] Set system preferences
- [x] Set language settings
- [x] Run database migration
- [x] Enable QuickBooks Webhooks Integration
- [x]     Set URL in QuickBooks API
- [x]     Set Verifier Token in ENV
- [x] Run all steps in QB page
- [ ] Prepare for Customer de-enrollment
- [x] Setup CRON job for QB refresh every 12 hours
- [x] Change Dev back to real QB data
- [x] Disable sync on QB for Dev
- [ ] Remove code from qb/attach_products_to_service()
