### ISSUE TITLE
Deployment Checklist

### ISSUE THREAD

**Issue by varlenthegray** [varlenthegray/wcadmin#295]
- [x] Run SQL code to migrate client data to service record 
- [x] Fetch QuickBooks Customer data again
- [x] Uncomment Telnyx lookup for QuickBooks Fetch Client
- [x] Run email migration ([migrate_to_record](https://wcadev.innovated.tech/email/migrate_to_record))
- [x] Run text message migration ([migrate_text_client_record](https://wcadev.innovated.tech/email/text_migrate_client_record))
- [x] Remove primary_client from service/models.py
- [x] Remove client from communication/models.py
- [x] Run SQL code below

```sql
UPDATE communication_sentemail SET subject = REPLACE(subject, '#<button', '<button') WHERE subject LIKE '%#<button%';
UPDATE communication_sentemail SET message = REPLACE(message, '#<button', '<button') WHERE message LIKE '%#<button%';

alter table communication_sentemail_to_clients
    drop constraint communication_sentem_sentemail_id_a4eddd22_fk_communica;

alter table communication_sentemail_to_clients
    add constraint communication_sentem_sentemail_id_a4eddd22_fk_communica
        foreign key (sentemail_id) references communication_sentemail
            on delete cascade
            deferrable initially deferred;

alter table communication_sentemail_to_records
    drop constraint communication_sentem_sentemail_id_413548be_fk_communica;

alter table communication_sentemail_to_records
    add constraint communication_sentem_sentemail_id_413548be_fk_communica
        foreign key (sentemail_id) references communication_sentemail
            on delete cascade
            deferrable initially deferred;

DELETE FROM communication_sentemail
WHERE id IN (
  SELECT id
  FROM (
    SELECT id,
           ROW_NUMBER() OVER (partition BY send_to, send_cc, subject, message, quickbooks_email, status, sent_by_id, template_id ORDER BY id) AS rnum
    FROM communication_sentemail
  ) t
  WHERE t.rnum > 1
);
```
